### ISSUE TITLE
pydst installation problems

### ISSUE THREAD

**Issue by HanzoChristo** [NumEconCopenhagen/IntroProg-lectures#11]
I'm having problems with installing/using pydst.

Running `pip install pydst` in cmd terminal/Anaconda Prompt gives the errors:
ERROR: Could not find a version that satisfies the requirement pydst (from versions: none)
ERROR: No matching distribution found for pydst

When installing from the pydst GitHub repository using `pip install git+https://github.com/Kristianuruplarsen/pydst.git`, the installation seems to succeed. Now, the package even shows up on the list when running `pip list` as 'pydst' (v. 0.2.0), but when I run `import pydst` in VS Code, I get the error:
No module named 'pydst'

I have tried on both Windows 10 and Windows 11.

**Comment by AskerNC** [comment]
Hi
It seems you're actually using an older version of the lecture  notebooks, we've switched from using pydst (previous years) and are now using [dstapi](https://github.com/alemartinello/dstapi)  using `pip install git+https://github.com/alemartinello/dstapi`
It's weird to me that pydst does not work, but since we're using dstapi now, I would just stick to that (let me know we that doesn't work either then something is really wrong 
In order to update to the latest version of the lecture notebooks (assuming you have git clonned the lectures following the [course guide](https://sites.google.com/view/numeconcph-introprog/guides/git)
You need to open vs code -> open the lecture folder you have cloned -> press crtl+shift+P and the write `git: sync`

**Comment by gpl942** [comment]
> Hi It seems you're actually using an older version of the lecture notebooks, we've switched from using pydst (previous years) and are now using [dstapi](https://github.com/alemartinello/dstapi) using `pip install git+https://github.com/alemartinello/dstapi` It's weird to me that pydst does not work, but since we're using dstapi now, I would just stick to that (let me know we that doesn't work either then something is really wrong In order to update to the latest version of the lecture notebooks (assuming you have git clonned the lectures following the [course guide](https://sites.google.com/view/numeconcph-introprog/guides/git) You need to open vs code -> open the lecture folder you have cloned -> press crtl+shift+P and the write `git: sync`

Hi Asker
I'm having the same problem, within Problem Set 4. 
I've uploaded the git exercise folders of both Jeppe and the TA but the notebook does not seem to change and it's still using code with pydst. I've also checked the files in the repository directly on github and tehy seem to be using pydst still (link [here](https://github.com/NumEconCopenhagen/IntroProg-exercises/blob/master/PS4/problem_set_4.ipynb)).
I was wondering if its there any other repository that I should check to find the updated file.

All the best

**Comment by gpl942** [comment]
> Hi It seems you're actually using an older version of the lecture notebooks, we've switched from using pydst (previous years) and are now using [dstapi](https://github.com/alemartinello/dstapi) using `pip install git+https://github.com/alemartinello/dstapi` It's weird to me that pydst does not work, but since we're using dstapi now, I would just stick to that (let me know we that doesn't work either then something is really wrong In order to update to the latest version of the lecture notebooks (assuming you have git clonned the lectures following the [course guide](https://sites.google.com/view/numeconcph-introprog/guides/git) You need to open vs code -> open the lecture folder you have cloned -> press crtl+shift+P and the write `git: sync`

Hi Asker
I'm having the same problem, within Problem Set 4. 
I've uploaded the git exercise folders of both Jeppe and the TA but the notebook does not seem to change and it's still using code with pydst. I've also checked the files in the repository directly on github and tehy seem to be using pydst still (link [here](https://github.com/NumEconCopenhagen/IntroProg-exercises/blob/master/PS4/problem_set_4.ipynb)).
I was wondering if its there any other repository that I should check to find the updated file.

All the best

**Comment by AskerNC** [comment]
Hi
Ohh this is my mistake, I've forgotten to update the problem sets with the DstApi change 
I apologize for this blunder, I'll fix it as soon as possible
