### ISSUE TITLE
Folder for exam project

### ISSUE THREAD

**Issue by viktortexel** [NumEconCopenhagen/IntroProg-lectures#17]
Hi!

Will a "template"-folder be created for the exam project in github upon starting the exam (similarly to the folders used for inaugural-, data- and modelproject, with a READ.ME, ipynb and py-file) - or do we have to create one ourselves ahead of the exam? 

Kind regards, 
Jos, P and Tex

**Comment by AskerNC** [comment]
Hi 

You should add an exam folder to your existing project on Github yourselves.

Best regards
Asker

**Comment by vkt823** [comment]
Hi,

What should the readme files include wrt. id? Should we list our exam number, names or our studyid?

kind regards,
Anders and Christian

**Comment by AskerNC** [comment]
Hi
You can just write your group name (but it's not that important since the other IDs are easy to find 
Best regards 
Asker
