### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by serkor1** [NumEconCopenhagen/IntroProg-lectures#19]
Hi @AskerNC,

1. Is it correctly understood that we have to create the `repository` on our own profile, and then you `fork` it? 
2. Is it possible to get invited to the `NumEconCopenhagen`-organization from our personal profiles?

Best,

**Comment by AskerNC** [comment]
Hi Sekor1
Thank you for your questions

1. If you are talking about your group repositories for handing in the assignments, then no: when you follow the invitation link: https://classroom.github.com/a/4JNBSrgL  (from the [guide](https://sites.google.com/view/numeconcph-introprog/guides/git) ) and create a new team, then a new repository will automatically be created under https://github.com/NumEconCopenhagen/projects-2024-YOURGROUPNAME of which you will be admin, so you can clone it and commit changes. 
2.  It shouldn't be a problem, try following the guide using your personal profiles and let me know if it doesn't work. 
For DataCamp it is however important for you to register using your alumni.ku.dk emails to get free access to all the courses

Best regards,
Asker

**Comment by serkor1** [comment]
Hi @AskerNC,

Everything works like a charm - thank you. I missed that part of the guide. 
And yes, I can join the organization using my personal profile! 🥇 

Best,
