### ISSUE TITLE
Plot in question 2? 

### ISSUE THREAD

**Issue by juliekrabek123** [NumEconCopenhagen/IntroProg-lectures#3]
Questions 2 askes for a plot of log(HF/HM) against log(wF/wM) for different values of wF. 
Should we display the values of wF or are they implicit? 
Should it be 2- or 3-dimensional? Or is it better to mark the wF values in the 2-dimentional plot? 
And to be clear - what do you want on which axis? 
Thanks!

**Comment by JeppeDruedahl** [comment]
On the x-axis: log(wF/wM) for fixed wM and wF in the specified list.
On the y-axis: log(HF/HM)
