### ISSUE TITLE
Juyter size

### ISSUE THREAD

**Issue by CesarArriaga** [NumEconCopenhagen/IntroProg-lectures#5]
Hi my problem is that I want to import my file with the code to the main Jupyter notebook so I can print the solutions but it says that the size limit has been passed and therefore I can't use my file in the notebook.

**Comment by JeppeDruedahl** [comment]
Í have not heard of the problem before. Please provide more details on the commands you are using. Otherwise talk with the TA in your exercise class.

**Comment by CesarArriaga** [comment]
so the problem is that when I try to open a Jupyter notebook it appears this problem: that it seems that I don't have the right extension

**Comment by AskerNC** [comment]
I haven't heard of this before either
Have you checked whether you have installed the Jupyter extension to vs code? 
You can see your extensions by pressing Ctrl+Shift+X in vs code.
Perhaps try uninstalling and reinstalling it.

Can you provide more information on what exactly you're doing (you're opening the notebook file in vs code?)
And exactly which message vs code gives you?
