### ISSUE TITLE
method "solve_wF_vec"

### ISSUE THREAD

**Issue by Virginia-Bergamasco** [NumEconCopenhagen/IntroProg-lectures#7]
In the “HouseholdSpecializationModel.py” file there is the method “solve_wF_vec”, for which we have to write the code, after the method “solve” for solving the model continuously. For what point/points of the project should we use it?

Thank you a lot for the information!

**Comment by AskerNC** [comment]
Hi 
This is meant for question 2 (and also used in Q3-5), as the vector of female wages references in the comment is the grid $[0.8,0.9,1.0,1.1,1.2]$. 
You are not strictly required to use the method or write it. (A more straightforward approach in question 3 would be to have a loop in the notebook over the vector of female wages solving the model). But especially for questions 4-5, the method becomes very convenient to have as part of the class.
