### ISSUE TITLE
Peer feedback in groups or not?

### ISSUE THREAD

**Issue by tbk642** [NumEconCopenhagen/IntroProg-lectures#9]
My group in I are wondering if the peer feedback is supposed to be done in the groups or individually? My team has gotten feedback in both ways and the lecture slides combined with the google spreadsheet are a bit ambiguous

**Comment by AskerNC** [comment]
Feedback is assigned at the group level. Of course, everyone in the group should contribute to the feedback, but you're free to either give one collected feedback or each member giving their separate feedback.

I apologize for the confusion, in previous years it has been at the person level.

Best,
Asker
